<a href="https://colab.research.google.com/github/Alexandr20i/Th_coding/blob/main/Th_coding_LR1_Belov_Vinogradov_Grigorev_Semenickhin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#  Лабораторная работа №1

## 1.1 Реализовать функцию REF(), приводящую матрицу к ступенчатому виду.

In [2]:
import numpy as np

In [1]:

def gaussian_elimination(matrix):
    mat = matrix.copy()  # Создаём копию матрицы для модификации

    # Определяем количество строк и столбцов
    num_rows, num_cols = mat.shape
    current_row = 0  # Изначально находимся на первой строке

    for col in range(num_cols):
        # Ищем строку с ненулевым элементом в текущем столбце
        pivot = None
        for r in range(current_row, num_rows):
            if mat[r, col] != 0:
                pivot = r
                break

        # Если подходящий элемент не найден, переходим к следующему столбцу
        if pivot is None:
            continue

        # Меняем местами текущую строку и строку с найденным ведущим элементом
        mat[[current_row, pivot]] = mat[[pivot, current_row]]

        # Для всех строк ниже текущей, если в них есть единица в этом столбце, вычитаем (по модулю 2)
        for r in range(current_row + 1, num_rows):
            if mat[r, col] != 0:
                mat[r] = (mat[r] + mat[current_row]) % 2

        # Переходим к следующей строке
        current_row += 1

    return mat


In [3]:
matrix = np.random.randint(0, 2, size=(3, 6))
print(matrix)

[[0 0 1 0 0 1]
 [1 1 0 0 0 0]
 [1 0 0 1 0 0]]


In [4]:
result = gaussian_elimination(matrix)
print(result)

[[1 1 0 0 0 0]
 [0 1 0 1 0 0]
 [0 0 1 0 0 1]]


## 1.2 Реализовать функцию RREF(), приводящую матрицу к приведённому ступенчатому виду.

In [7]:
def reduced_row_echelon(matrix):
    mat = matrix.copy()  # Копия матрицы для изменения

    # Получаем количество строк и столбцов
    num_rows, num_cols = mat.shape
    current_row = 0  # Начинаем с первой строки

    for col in range(num_cols):
        # Находим строку с ненулевым элементом в текущем столбце
        pivot = None
        for row in range(current_row, num_rows):
            if mat[row, col] != 0:
                pivot = row
                break

        # Если нет ведущего элемента, продолжаем с следующего столбца
        if pivot is None:
            continue

        # Меняем местами текущую строку и строку с найденным ведущим элементом
        mat[[current_row, pivot]] = mat[[pivot, current_row]]

        # Применяем сложение по модулю 2 ко всем строкам ниже
        for row in range(num_rows):
            if row != current_row and mat[row, col] != 0:
                mat[row] = (mat[row] + mat[current_row]) % 2

        current_row += 1

        # Если дошли до последней строки, прекращаем
        if current_row >= num_rows:
            break

    return mat

In [8]:
matrix = np.random.randint(0, 2, size=(5, 6))
print(matrix)

[[1 0 1 1 1 1]
 [1 1 0 1 0 0]
 [0 0 1 0 0 0]
 [0 1 0 1 0 1]
 [0 0 0 0 1 1]]


In [9]:
result = reduced_row_echelon(matrix)
print(result)

[[1 0 0 0 0 1]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 1]
 [0 0 0 0 1 1]]


## 1.3 Создать класс линейных кодов LinearCode.

### 1.3.1 На основе входной матрицы сформировать порождающую матрицу в ступенчатом виде.

In [10]:
S = np.array([[1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1],
             [0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0],
             [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
             [1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1],
             [0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0],
             [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]])
S_REF = reduced_row_echelon(S)
print(S_REF)

[[1 0 0 0 0 1 1 0 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 1 1 0 1 0]
 [0 0 0 1 0 1 1 1 0 0 1]
 [0 0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 0 0 0 0 1 0 1]]


### 1.3.2 Задать n равное числу столбцов и k равное числу строк полученной матрицы (без учёта полностью нулевых строк).

In [11]:
def remove_zero_rows(matrix):
    # Удаляем строки, которые полностью состоят из нулей
    filtered_matrix = matrix[~np.all(matrix == 0, axis=1)]

    # Получаем количество строк и столбцов в новой матрице
    num_rows = filtered_matrix.shape[0]
    num_cols = filtered_matrix.shape[1]

    return num_cols, num_rows

In [13]:
G = np.random.randint(0, 2, size=(5, 6))
print(G)

[[0 0 0 0 0 0]
 [1 1 0 1 1 0]
 [1 1 0 0 0 0]
 [0 0 0 0 0 1]
 [1 1 0 0 0 1]]


In [14]:
result = reduced_row_echelon(G)
print(result)

[[1 1 0 0 0 0]
 [0 0 0 1 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [15]:
n,k = remove_zero_rows(result)
print(f" n = {n} \n k = {k}")

 n = 6 
 k = 3


### 1.3.3 Сформировать проверочную матрицу на основе порождающей.

In [16]:
# Шаг 1. Сформировать матрицу 𝐆∗ в приведённом ступенчатом виде на основе порождающей.
S = np.array([[1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1],
             [0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0],
             [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
             [1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1],
             [0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0],
             [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]])
matrix = reduced_row_echelon(S)
print(matrix)

[[1 0 0 0 0 1 1 0 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 1 1 0 1 0]
 [0 0 0 1 0 1 1 1 0 0 1]
 [0 0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 0 0 0 0 1 0 1]]


In [17]:
def identify_pivots(matrix):
    # Получаем количество строк и столбцов
    num_rows, num_cols = matrix.shape
    pivot_columns = []  # Список для хранения индексов ведущих столбцов

    # Ищем ведущий элемент в каждой строке
    for row in range(num_rows):
        for col in range(num_cols):
            if matrix[row, col] == 1:
                # Если нашли ведущий элемент, фиксируем индекс столбца
                pivot_columns.append(col)
                break  # Переходим к следующей строке

    return pivot_columns

# Пример использования функции
pivot_indices = identify_pivots(matrix)
print(f"Ведущие столбцы: {pivot_indices}")

Ведущие столбцы: [0, 1, 2, 3, 4, 8]


In [18]:
# Шаг 3. Сформировать сокращённую матрицу 𝐗, удалив ведущие столбцы матрицы 𝐆∗.
# Удаляем ведущие столбцы, оставляя только остальные
H3 = np.delete(matrix, pivot_indices, axis=1)

print("Сокращённая матрица X:")
print(H3)

Сокращённая матрица X:
[[1 1 0 0 0]
 [0 0 1 0 0]
 [0 1 1 1 0]
 [1 1 1 0 1]
 [0 1 1 1 1]
 [0 0 0 0 1]]


In [20]:
import numpy as np

def create_matrix_without_null(matrix):
    # Получаем количество строк и столбцов, исключая нулевые строки
    num_rows, num_cols = matrix.shape
    filtered_matrix = matrix[~np.all(matrix == 0, axis=1)]

    return filtered_matrix.shape[1], filtered_matrix.shape[0]

def construct_matrix(leading_columns, matrix_X, num_rows_X, matrix_identity, num_rows_identity):
    # Инициализируем индексы для матрицы результата
    index_X = 0
    index_identity = 0
    result_matrix = []

    # Объединяем строки из матрицы X и единичной матрицы в соответствии с ведущими столбцами
    for i in range(num_rows_identity + num_rows_X):
        if index_X < len(leading_columns) and i == leading_columns[index_X]:
            result_matrix.append(matrix_X[index_X])
            index_X += 1
        else:
            result_matrix.append(matrix_identity[index_identity])
            index_identity += 1

    return np.array(result_matrix)

# Пример использования
nH3, kH3 = create_matrix_without_null(H3)
nH4 = max(nH3, kH3)
H4 = np.eye(nH3, dtype=int)

result = construct_matrix(pivot_indices, H3, nH3, H4, nH4)
print(result)


[[1 1 0 0 0]
 [0 0 1 0 0]
 [0 1 1 1 0]
 [1 1 1 0 1]
 [0 1 1 1 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 0 0 1]]


## 1.4 Сформировать все кодовые слова длины n двумя способами.

### 1.4.1 Сложить все слова из порождающего множества, оставить неповторяющиеся.


In [28]:
# Функция для генерации уникальных кодовых слов из порождающего множества
def generate_unique_words(G):
    unique_words = set()
    rows, cols = G.shape

    for i in range(1, 2**rows):
        result = np.zeros(cols, dtype=int)
        for j in range(rows):
            if (i >> j) & 1:
                result = (result + G[j]) % 2
        unique_words.add(tuple(result))

    return np.array(list(unique_words))

In [27]:
G = np.array([[1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
              [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
              [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
              [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])

M = np.array([[0, 1, 0, 0],  # строка 1
              [0, 0, 1, 1],  # строка 2
              [1, 1, 0, 0]]) # строка 4

H = np.array([[0, 1, 1, 1, 1, 0],
             [1, 0, 0, 0, 0, 0],
             [0, 1, 0, 0, 0, 0],
             [0, 0, 1, 0, 1, 1],
             [0, 0, 0, 1, 0, 1],
             [0, 0, 1, 0, 0, 0],
             [0, 0, 0, 0, 1, 0],
             [0, 0, 0, 1, 0, 0],
             [0, 0, 0, 0, 1, 1],
             [0, 0, 0, 0, 1, 0],
             [0, 0, 0, 0, 0, 1]])


In [29]:
# Генерация кодовых слов
unique_words = generate_unique_words(M)
print(unique_words)


[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 1]
 [1 1 1 1]]


### 1.4.2 Взять все двоичные слова длины k, умножить каждое на G.


In [30]:
# 1.4.2 Взять все двоичные слова длины k, умножить каждое на G.

u = np.array([1, 0, 1, 1, 0])
print('u = ', u)

v = np.dot(u,G)
v %= 2
print('v = u@G ', v)

check = np.dot(v, H)
check %= 2
print('v@H =', check)

u =  [1 0 1 1 0]
v = u@G  [1 0 1 1 1 0 1 0 0 1 0]
v@H = [0 0 0 0 0 0]


## 1.5 Вычислить кодовое расстояние получившегося кода.


In [31]:
from itertools import combinations

# Функция для вычисления кодового расстояния
def calculate_code_distance(matrix):
    # Устанавливаем начальное большое значение для минимального веса
    min_weight = np.inf

    # Перебираем все возможные комбинации строк матрицы (от 1 до всех строк)
    for size in range(1, len(matrix) + 1):
        for subset in combinations(matrix, size):
            # Создаем результирующий вектор как сумму строк по модулю 2
            result_vector = np.zeros(len(matrix[0]), dtype=int)

            # Проход по каждой строке из подмножества
            for row in subset:
                result_vector = (result_vector + row) % 2

            # Вычисляем вес (количество ненулевых элементов) результирующего вектора
            weight = np.sum(result_vector)

            # Обновляем минимальный вес, если найден новый
            if 0 < weight < min_weight:
                min_weight = weight

    return int(min_weight)

In [32]:
G = np.array([[1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
              [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
              [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
              [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])

In [33]:
# Размерность матрицы G
n = G.shape[1]  # Число столбцов
k = G.shape[0]  # Число строк
print('n =', n, '\nk =', k)

# Вычисляем минимальное кодовое расстояние
d = calculate_code_distance(G)

# Вычисляем кратность обнаруживаемой ошибки
t = d - 1  # или можно оставить t = (d - 1) // 2, в зависимости от требования
print("Кодовое расстояние (d) =", d)
print("Кратность обнаруживаемой ошибки (t) =", t)

n = 11 
k = 5
Кодовое расстояние (d) = 2
Кратность обнаруживаемой ошибки (t) = 1


### 1.5.1 Внести в кодовое слово ошибку кратности не более t, умножить полученное слово на H, убедиться в обнаружении ошибки.

In [34]:
v = np.array([1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0])
e1 = np.array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])
Ve1 = (v + e1) % 2
print('v+e1', Ve1)
check = np.dot(Ve1, H)
check %= 2
print('(v+e1)@H =', check, "- error")


v+e1 [1 0 0 1 1 0 1 0 0 1 0]
(v+e1)@H = [0 1 0 0 0 0] - error


### 1.5.2 Найти для некоторого кодового слова ошибку кратности t+1 такую, что при умножении на H ошибка не может быть обнаружена.


In [35]:
def detect_error_pattern(codeword, parity_check_matrix):
    # Перебираем все возможные пары позиций в кодовом слове
    for index1 in range(len(codeword) - 1):
        for index2 in range(index1 + 1, len(codeword)):
            # Формируем вектор ошибки для двух позиций
            error_vector = np.zeros(len(codeword), dtype=int)
            error_vector[[index1, index2]] = 1  # Устанавливаем единицы на выбранных позициях

            # Вектор с ошибкой
            corrupted_word = (codeword + error_vector) % 2

            # Проверка: умножаем на проверочную матрицу
            syndrome = np.dot(corrupted_word, parity_check_matrix) % 2

            # Если синдром состоит из всех нулей, значит ошибка не обнаружена
            if np.all(syndrome == 0):
                return error_vector  # Возвращаем найденный вектор ошибки

    return None  # Если ошибка не была обнаружена


In [36]:
e2 = detect_error_pattern(v, H)
print('e2', e2)

Ve2 = (v + e2) % 2
print('v+e2', Ve2)

check = np.dot(Ve2, H)
check %= 2
print('(v+e2)@H =', check, "- no error")

e2 [0 0 0 0 0 0 1 0 0 1 0]
v+e2 [1 0 1 1 1 0 0 0 0 0 0]
(v+e2)@H = [0 0 0 0 0 0] - no error
